apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: dstk

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus
  namespace: dstk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: dstk

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: dstk
  namespace: dstk
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/part-of: dstk
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: main
        port: web

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: prometheus-dstk
#spec:
#  type: NodePort
#  ports:
#    - name: web
#      nodePort: 30900
#      port: 9090
#      protocol: TCP
#      targetPort: web
#  selector:
#    prometheus: dstk


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prom
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: prom.kind
      http:
        paths:
          - backend:
              serviceName: prometheus-operated
              servicePort: web
