version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    network_mode: bridge
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: se
    volumes:
      - se-data2:/var/lib/postgresql/data/

volumes:
  se-data2:
