apiVersion: v1
kind: Service
metadata:
  name: {{ include "dc.fullname" . }}
  labels:
    {{- include "dc.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "dc.selectorLabels" . | nindent 4 }}
