apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dc.fullname" . }}
  labels:
    {{- include "dc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dc.labels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: 10s
