apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dc.fullname" . }}
  labels:
    {{- include "dc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "dc.selectorLabels" . | nindent 6 }}

  serviceName: {{ include "dc.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "dc.fullname" . }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.data.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.data.storage }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      volumes:
        - name: config-volume
          configMap:
            name: {{ include "dc.fullname" . }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: {{ include "dc.fullname" . }}
              mountPath: /data

          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          command:
            - "/dstk/disk-cache"

          args:
            - "--conf=/etc/config/dc.yaml"
            - "--log={{ .Values.logLevel }}"
            - "--clean-db={{ .Values.cleanDb }}"
            - "--name=$(NODE_NAME)"
          ports:
            - name: grpc
              containerPort: 6011
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.metricPort }}
              protocol: TCP
            - name: gw
              containerPort: 6013
              protocol: TCP
          #          livenessProbe:
          #            httpGet:
          #              path: /
          #              port: http
          #          readinessProbe:
          #            httpGet:
          #              path: /
          #              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
