Port: 6001
Driver: postgres
Mode: sql
ConnUrl: "host=127.0.0.1 user=postgres dbname=postgres sslmode=disable"
PasswdFile: /secrets/se/postgresql-password
Init:
  CleanExisting: true
  NumParts: 16
  Seed: 0
  Workers:
    - Id: 1
      Url: "localhost: 6011"
    - Id: 2
      Url: "localhost: 6021"
